[package]
name = "quorum-vault-client"
version = "0.1.0"
edition = "2021"

[dependencies]
vaultrs = "0.6.2"
web3 = "0.18.0"
derive_builder = "0.12.0"
thiserror = "1.0.38"
log = "0.4.17"
serde = "1.0.130"
serde_json = "1.0.91"
rustify = "0.5.3"
rustify_derive = "0.5.2"
eth_checksum = "0.1.2"
